# -------------------------------------------------------------------------------------------------
# Logging properties
# -------------------------------------------------------------------------------------------------
logging:
  level:
    ROOT: info