server:
  port: 8081

# -------------------------------------------------------------------------------------------------
# Logging properties
# -------------------------------------------------------------------------------------------------
logging:
  level:
    ROOT: info